plugins:
  plugin_name_enabled:
    default: false
    client: true
  radix_dapp_definition_address:
    default: ""
    client: true
  radix_network_id:
    default: 2
    client: true
  radix_application_name:
    default: ""
    client: true
  radix_application_version:
    default: "1.0.0"
    client: true
  radix_rola_api_url:
    default: ""
    client: true
